### ISSUE TITLE
Stufenverteilung Statistik - Verzerrung bei vielen Inaktiven (Sonstigen)

### ISSUE THREAD

**Issue by JanneckLange** [digital-scouts/dpsg-nami-app#105]
Bei Stämmen mit vielen Sonstigen Mitgliedern wird die Grafik Stufenverteilung stark verzerrt. 

Lösungs-Idee: Sonstige aus der Grafik raus nehmen und unter der Grafik nennen.

![image](https://github.com/digital-scouts/dpsg-nami-app/assets/26873867/99fc0a7c-a228-4884-afdb-3993aab39788)

**Comment by kolaente** [comment]
Ich hab das vorhin über die App reported, hier noch ein paar Infos dazu.

Bei uns im Nami sieht das so aus:

![image](https://github.com/digital-scouts/dpsg-nami-app/assets/13721712/aa7c046b-1406-4e70-826f-853ad290302c)

Vielleicht kann man das einfach nachbauen?

Wenn ich mir im nami unter "Mitgliederverwaltung" die Liste ausgebe, kommt da das hier raus:

```
curl 'https://nami.dpsg.de/ica/rest/nami/mitglied/filtered-for-navigation/gruppierung/gruppierung/330303/flist?_dc=1714068776946&page=1&start=0&limit=5000' -H 'Cookie: JSESSIONID=not-my-session-id; ICA-MGLVERW-SHOW-INAKTIVE-MGL=false' | jq '.data' | grep 'entries_stufe' | sort | uniq -c

     21     "entries_stufe": "",
     18     "entries_stufe": "Jungpfadfinder",
      8     "entries_stufe": "Pfadfinder",
     12     "entries_stufe": "Rover",
     12     "entries_stufe": "Wölfling",
```

Wenn ich den `ICA-MGLVERW-SHOW-INAKTIVE-MGL=false` Cookie weglasse, sieht das so aus:

```
    103     "entries_stufe": "",
     18     "entries_stufe": "Jungpfadfinder",
      8     "entries_stufe": "Pfadfinder",
     12     "entries_stufe": "Rover",
     12     "entries_stufe": "Wölfling",
```

Vermutlich ist das also die Ansicht, die du verwendest?

**Comment by JanneckLange** [comment]
<img width="261" alt="Bildschirmfoto 2024-04-29 um 13 31 59" src="https://github.com/digital-scouts/dpsg-nami-app/assets/26873867/af68fd5d-28a5-47a9-8cc7-41d1ad60d3f0">

Solved
