### ISSUE TITLE
Add to awesome-dpsg list

### ISSUE THREAD

**Issue by mstoetzer** [digital-scouts/dpsg-nami-app#25]
Hi, ich möchte Dein Repo gerne in die awesome-dpsg Liste aufnehmen: https://github.com/mstoetzer/awesome-dpsg

**Comment by JanneckLange** [comment]
Awesome sagt mir nichts, was hat es damit auf sich?
Ansonsten darfst du die Mami App gerne mit aufnehmen. Aber bitte als Work in Progress markieren

**Comment by mstoetzer** [comment]
Eine Awesome-Liste ist auf GitHub eine von der Community gepflegte Liste mit relevanten Dingen zu einem bestimmten Thema.

Übergeordnet finden sich hier alle Awesome-Listen auf Github: https://github.com/topics/awesome 

Für dich wäre vielleicht awesome-flutter interessant: https://github.com/Solido/awesome-flutter :)

Grüße
