### ISSUE TITLE
Statistik - dynamische Spannweiten

### ISSUE THREAD

**Issue by JanneckLange** [digital-scouts/dpsg-nami-app#58]
Stufenverteilung: Leere Stufen nicht anzeigen. 

Altersverteilung: Das jüngste und das älteste Mitglied definiert die Grenzen der Grafik um leere Bereiche zu vermeiden.  

![image](https://github.com/digital-scouts/dpsg-nami-app/assets/26873867/6c271fda-4956-413d-9b46-fbe3c241a5b9)

**Comment by Vinzent03** [comment]
Da die Stufenverteilung jetzt über die ganze Breite geht, finde ich, dass man auch leere Stufen anzeigen kann. 
Bei der Altersverteilung ist es mit #62 bereits behoben.
